package pro.trafficwrapper

import android.content.Context
import java.io.EOFException
import java.io.InputStream
import java.io.OutputStream
import java.security.MessageDigest
import java.security.SecureRandom
import org.json.JSONObject
import pro.trafficwrapper.go.transport.Transport

internal data class SocksCredentials(val username: String, val password: String) {
    override fun toString(): String = "SocksCredentials(username=$username, password=***)"
}

/**
 * Credentials for the loopback SOCKS/HTTP listeners.
 *
 * Internal credentials guard the upstream listeners (xray and AWG on 18081-18084) and are also
 * accepted by the front-end router, so in-process clients (probes, telemetry, updates, the VPN
 * bridge, the local HTTP proxy) always authenticate with them. They are generated by the Go core
 * once per process and never leave it.
 *
 * Front-end credentials are optional and user-visible: when enabled, the router on 18080 and the
 * HTTP proxy on 18090 stop accepting unauthenticated clients, so other apps on the device can no
 * longer use or fingerprint the tunnel without the password.
 */
internal object LocalSocksAuth {
    @Volatile
    private var internalOverride: SocksCredentials? = null

    val internal: SocksCredentials by lazy {
        internalOverride ?: parseCredentialsJson(Transport.localSOCKSAuth())
    }

    fun isFrontEndAuthEnabled(context: Context): Boolean =
        prefs(context).getBoolean(KEY_FRONT_END_ENABLED, false)

    fun setFrontEndAuthEnabled(context: Context, enabled: Boolean) {
        if (enabled) frontEndCredentials(context)
        prefs(context).edit().putBoolean(KEY_FRONT_END_ENABLED, enabled).apply()
    }

    /** Front-end credentials when front-end auth is enabled, otherwise null. */
    fun requiredFrontEndCredentials(context: Context): SocksCredentials? =
        if (isFrontEndAuthEnabled(context)) frontEndCredentials(context) else null

    @Synchronized
    fun frontEndCredentials(context: Context): SocksCredentials {
        val prefs = prefs(context)
        val username = prefs.getString(KEY_FRONT_END_USERNAME, null).orEmpty()
        val password = prefs.getString(KEY_FRONT_END_PASSWORD, null).orEmpty()
        if (username.isNotEmpty() && password.isNotEmpty()) return SocksCredentials(username, password)
        return regenerateFrontEndCredentials(context)
    }

    @Synchronized
    fun regenerateFrontEndCredentials(context: Context): SocksCredentials {
        val credentials = SocksCredentials(FRONT_END_USERNAME, randomToken(FRONT_END_PASSWORD_BYTES))
        prefs(context).edit()
            .putString(KEY_FRONT_END_USERNAME, credentials.username)
            .putString(KEY_FRONT_END_PASSWORD, credentials.password)
            .apply()
        return credentials
    }

    internal fun overrideInternalForTest(credentials: SocksCredentials) {
        internalOverride = credentials
    }

    private fun prefs(context: Context) =
        context.applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    private const val PREFS_NAME = "local_socks_auth"
    private const val KEY_FRONT_END_ENABLED = "front_end_enabled"
    private const val KEY_FRONT_END_USERNAME = "front_end_username"
    private const val KEY_FRONT_END_PASSWORD = "front_end_password"
    private const val FRONT_END_USERNAME = "tw"
    private const val FRONT_END_PASSWORD_BYTES = 12
}

internal fun parseCredentialsJson(json: String): SocksCredentials {
    val obj = JSONObject(json)
    val error = obj.optString("error")
    require(error.isEmpty()) { "local socks auth unavailable: $error" }
    val username = obj.optString("username")
    val password = obj.optString("password")
    require(username.isNotEmpty() && password.isNotEmpty()) { "local socks auth is empty" }
    return SocksCredentials(username, password)
}

private val secureRandom = SecureRandom()

internal fun randomToken(bytes: Int): String {
    val raw = ByteArray(bytes)
    secureRandom.nextBytes(raw)
    return raw.joinToString("") { "%02x".format(it.toInt() and 0xff) }
}

internal fun constantTimeEquals(a: String, b: String): Boolean =
    MessageDigest.isEqual(a.toByteArray(Charsets.UTF_8), b.toByteArray(Charsets.UTF_8))

/** RFC 1928/1929 method negotiation helpers shared by every loopback SOCKS client and server. */
internal object Socks5Auth {
    const val VERSION = 0x05
    const val METHOD_NO_AUTH = 0x00
    const val METHOD_USER_PASS = 0x02
    const val METHOD_NO_ACCEPTABLE = 0xff
    private const val USER_PASS_VERSION = 0x01
    private const val BYTE_MASK = 0xff

    /** Client side: offer user/pass when [credentials] are set, otherwise no-auth only. */
    fun negotiateClient(input: InputStream, output: OutputStream, credentials: SocksCredentials?) {
        val method = if (credentials != null) METHOD_USER_PASS else METHOD_NO_AUTH
        output.write(byteArrayOf(VERSION.toByte(), 1, method.toByte()))
        output.flush()
        val version = readByte(input)
        val selected = readByte(input)
        if (version != VERSION || selected != method) {
            throw EOFException("socks method rejected: $version/$selected")
        }
        if (credentials == null) return
        val user = credentials.username.toByteArray(Charsets.UTF_8)
        val pass = credentials.password.toByteArray(Charsets.UTF_8)
        require(user.size in 1..255 && pass.size in 1..255) { "socks credentials length is invalid" }
        output.write(byteArrayOf(USER_PASS_VERSION.toByte(), user.size.toByte()) + user + byteArrayOf(pass.size.toByte()) + pass)
        output.flush()
        readByte(input)
        if (readByte(input) != 0) throw EOFException("socks authentication failed")
    }

    /**
     * Server side. When [accepted] is empty, no-auth is accepted. Otherwise the client must offer
     * user/pass and present one of the accepted credential pairs. Returns the matched credentials
     * (or null for no-auth); throws after replying with a failure when authentication fails.
     */
    fun negotiateServer(input: InputStream, output: OutputStream, accepted: List<SocksCredentials>): SocksCredentials? {
        if (readByte(input) != VERSION) throw EOFException("bad socks version")
        val count = readByte(input)
        val methods = ByteArray(count)
        readFully(input, methods)
        val offered = methods.map { it.toInt() and BYTE_MASK }.toSet()
        if (accepted.isEmpty()) {
            if (METHOD_NO_AUTH !in offered) {
                output.write(byteArrayOf(VERSION.toByte(), METHOD_NO_ACCEPTABLE.toByte()))
                output.flush()
                throw EOFException("socks client offered no no-auth method")
            }
            output.write(byteArrayOf(VERSION.toByte(), METHOD_NO_AUTH.toByte()))
            output.flush()
            return null
        }
        if (METHOD_USER_PASS !in offered) {
            output.write(byteArrayOf(VERSION.toByte(), METHOD_NO_ACCEPTABLE.toByte()))
            output.flush()
            throw EOFException("socks client did not offer user/pass")
        }
        output.write(byteArrayOf(VERSION.toByte(), METHOD_USER_PASS.toByte()))
        output.flush()
        if (readByte(input) != USER_PASS_VERSION) throw EOFException("bad socks auth version")
        val user = ByteArray(readByte(input)).also { readFully(input, it) }.toString(Charsets.UTF_8)
        val pass = ByteArray(readByte(input)).also { readFully(input, it) }.toString(Charsets.UTF_8)
        val matched = accepted.firstOrNull {
            constantTimeEquals(it.username, user) and constantTimeEquals(it.password, pass)
        }
        output.write(byteArrayOf(USER_PASS_VERSION.toByte(), if (matched != null) 0 else 1))
        output.flush()
        return matched ?: throw EOFException("socks authentication failed")
    }

    private fun readByte(input: InputStream): Int {
        val value = input.read()
        if (value < 0) throw EOFException()
        return value
    }

    private fun readFully(input: InputStream, buffer: ByteArray) {
        var offset = 0
        while (offset < buffer.size) {
            val read = input.read(buffer, offset, buffer.size - offset)
            if (read < 0) throw EOFException()
            offset += read
        }
    }
}
