package pro.trafficwrapper

import android.content.Context
import java.io.EOFException
import java.io.InputStream
import java.io.OutputStream
import java.security.MessageDigest
import java.security.SecureRandom
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec
import org.json.JSONObject
import pro.trafficwrapper.go.transport.Transport

internal data class SocksCredentials(val username: String, val password: String) {
    override fun toString(): String = "SocksCredentials(username=$username, password=***)"
}

/** Fixed loopback port of the front-end SOCKS router. */
internal const val LOCAL_ROUTER_PORT = 18080

/**
 * Credentials for the loopback SOCKS/HTTP listeners.
 *
 * Internal credentials guard the upstream listeners (xray and AWG on 18081-18084) and are also
 * accepted by the front-end router, so in-process clients (probes, telemetry, updates, the VPN
 * bridge, the local HTTP proxy) always authenticate with them. They are generated by the Go core
 * once per process and never leave it. Towards the router on the fixed port 18080 in-process
 * clients use the router proof (see [Socks5Auth.negotiateRouterProofClient]) instead of sending
 * the credentials, because another app may hold that port while the router is not listening.
 *
 * Front-end credentials are user-visible: when enabled, the router on 18080 and the HTTP proxy on
 * 18090 stop accepting unauthenticated clients. In VPN mode the listeners never accept
 * unauthenticated clients (apps already reach the tunnel through the VPN interface).
 */
internal object LocalSocksAuth {
    @Volatile
    private var internalCached: SocksCredentials? = null

    val internal: SocksCredentials
        get() = internalCached ?: synchronized(this) {
            internalCached ?: parseCredentialsJson(Transport.localSOCKSAuth()).also { internalCached = it }
        }

    /** True when [credentials] are the (already resolved) internal credentials of this process. */
    fun isInternal(credentials: SocksCredentials?): Boolean {
        val resolved = internalCached ?: return false
        return credentials != null && credentials == resolved
    }

    fun isFrontEndAuthEnabled(context: Context): Boolean {
        val prefs = prefs(context)
        if (prefs.contains(KEY_FRONT_END_ENABLED)) return prefs.getBoolean(KEY_FRONT_END_ENABLED, false)
        return synchronized(this) {
            if (prefs.contains(KEY_FRONT_END_ENABLED)) {
                prefs.getBoolean(KEY_FRONT_END_ENABLED, false)
            } else {
                // First read on this install: decide once and persist the decision.
                val enabled = frontEndAuthDefault(stored = null, existingInstall = hasExistingInstallState(context))
                if (enabled) frontEndCredentials(context)
                prefs.edit().putBoolean(KEY_FRONT_END_ENABLED, enabled).apply()
                enabled
            }
        }
    }

    fun setFrontEndAuthEnabled(context: Context, enabled: Boolean) {
        if (enabled) frontEndCredentials(context)
        prefs(context).edit().putBoolean(KEY_FRONT_END_ENABLED, enabled).apply()
    }

    /** Front-end credentials when front-end auth is enabled, otherwise null. */
    fun requiredFrontEndCredentials(context: Context): SocksCredentials? =
        if (isFrontEndAuthEnabled(context)) frontEndCredentials(context) else null

    /** Effective policy of the router (18080) and the HTTP proxy (18090) for other apps. */
    fun proxyAuthPolicy(context: Context): LocalProxyAuthPolicy =
        localProxyAuthPolicy(
            vpnMode = BuildConfig.VPN_ENABLED && TransportLifecycleStore.vpnEnabled(context),
            frontEnd = requiredFrontEndCredentials(context),
        )

    @Synchronized
    fun frontEndCredentials(context: Context): SocksCredentials {
        val prefs = prefs(context)
        val username = prefs.getString(KEY_FRONT_END_USERNAME, null).orEmpty()
        val password = prefs.getString(KEY_FRONT_END_PASSWORD, null).orEmpty()
        if (username.isNotEmpty() && password.isNotEmpty()) return SocksCredentials(username, password)
        return regenerateFrontEndCredentials(context)
    }

    @Synchronized
    fun regenerateFrontEndCredentials(context: Context): SocksCredentials {
        val credentials = SocksCredentials(FRONT_END_USERNAME, randomToken(FRONT_END_PASSWORD_BYTES))
        prefs(context).edit()
            .putString(KEY_FRONT_END_USERNAME, credentials.username)
            .putString(KEY_FRONT_END_PASSWORD, credentials.password)
            .apply()
        return credentials
    }

    internal fun overrideInternalForTest(credentials: SocksCredentials) {
        internalCached = credentials
    }

    /**
     * An installation that existed before this version: it was updated (not freshly installed)
     * or it already holds enrollment state. Such installs keep proxy auth off unless the user
     * turned it on, so configured integrations keep working.
     */
    private fun hasExistingInstallState(context: Context): Boolean {
        val appContext = context.applicationContext
        val updated = runCatching {
            @Suppress("DEPRECATION")
            val info = appContext.packageManager.getPackageInfo(appContext.packageName, 0)
            info.lastUpdateTime > info.firstInstallTime
        }.getOrDefault(true)
        if (updated) return true
        val secure = appContext.getSharedPreferences(SECURE_PREFS_NAME, Context.MODE_PRIVATE)
        return ENROLLMENT_STATE_KEYS.any { secure.contains(it) }
    }

    private fun prefs(context: Context) =
        context.applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    private const val PREFS_NAME = "local_socks_auth"
    private const val KEY_FRONT_END_ENABLED = "front_end_enabled"
    private const val KEY_FRONT_END_USERNAME = "front_end_username"
    private const val KEY_FRONT_END_PASSWORD = "front_end_password"
    private const val FRONT_END_USERNAME = "tw"
    private const val FRONT_END_PASSWORD_BYTES = 12

    // Names owned by SecureIdentityStore; only their presence is checked here.
    private const val SECURE_PREFS_NAME = "trafficwrapper_secure"
    private val ENROLLMENT_STATE_KEYS = listOf("identity", "session", "public_platform_state")
}

/** Stored value wins; otherwise new installs require a password and existing installs do not. */
internal fun frontEndAuthDefault(stored: Boolean?, existingInstall: Boolean): Boolean =
    stored ?: !existingInstall

/**
 * What the router and the HTTP proxy accept from clients that do not hold the internal
 * credentials: [frontEnd] credentials when set, unauthenticated clients only when [allowNoAuth].
 */
internal data class LocalProxyAuthPolicy(val allowNoAuth: Boolean, val frontEnd: SocksCredentials?) {
    /** Changes whenever sessions admitted under the previous policy must be dropped. */
    val fingerprint: String
        get() = when {
            frontEnd != null -> "pw:" + sha256Hex("${frontEnd.username}\u0000${frontEnd.password}").take(16)
            allowNoAuth -> "open"
            else -> "internal"
        }
}

internal fun localProxyAuthPolicy(vpnMode: Boolean, frontEnd: SocksCredentials?): LocalProxyAuthPolicy =
    LocalProxyAuthPolicy(allowNoAuth = frontEnd == null && !vpnMode, frontEnd = frontEnd)

private fun sha256Hex(value: String): String =
    MessageDigest.getInstance("SHA-256")
        .digest(value.toByteArray(Charsets.UTF_8))
        .joinToString("") { "%02x".format(it.toInt() and 0xff) }

internal fun parseCredentialsJson(json: String): SocksCredentials {
    val obj = JSONObject(json)
    val error = obj.optString("error")
    require(error.isEmpty()) { "local socks auth unavailable: $error" }
    val username = obj.optString("username")
    val password = obj.optString("password")
    require(username.isNotEmpty() && password.isNotEmpty()) { "local socks auth is empty" }
    return SocksCredentials(username, password)
}

private val secureRandom = SecureRandom()

internal fun randomToken(bytes: Int): String {
    val raw = ByteArray(bytes)
    secureRandom.nextBytes(raw)
    return raw.joinToString("") { "%02x".format(it.toInt() and 0xff) }
}

internal fun constantTimeEquals(a: String, b: String): Boolean =
    MessageDigest.isEqual(a.toByteArray(Charsets.UTF_8), b.toByteArray(Charsets.UTF_8))

/** Thrown by a client when the router address is held by a listener that failed the proof. */
internal class UntrustedSocksRouterException(message: String) : EOFException(message)

/** RFC 1928/1929 method negotiation helpers shared by every loopback SOCKS client and server. */
internal object Socks5Auth {
    const val VERSION = 0x05
    const val METHOD_NO_AUTH = 0x00
    const val METHOD_USER_PASS = 0x02
    const val METHOD_NO_ACCEPTABLE = 0xff

    /**
     * Private method (RFC 1928 range 0x80-0xFE) between in-process clients and the router: both
     * sides prove knowledge of the internal password with HMAC-SHA256 over fresh nonces, the
     * listener first, so the credentials are never sent to whoever holds the port. The wire
     * format is shared with the Go core (core/transport/socks_auth.go).
     */
    const val METHOD_ROUTER_PROOF = 0x86
    private const val ROUTER_PROOF_VERSION = 0x01
    const val ROUTER_NONCE_BYTES = 32
    private const val ROUTER_MAC_BYTES = 32
    private const val ROUTER_SERVER_LABEL = "tw-router-server-v1"
    private const val ROUTER_CLIENT_LABEL = "tw-router-client-v1"
    private const val USER_PASS_VERSION = 0x01
    private const val BYTE_MASK = 0xff

    /**
     * Client side: offer user/pass when [credentials] are set, otherwise no-auth only. Towards the
     * router ([peerPort] == [LOCAL_ROUTER_PORT]) the internal credentials are replaced by the
     * router proof.
     */
    fun negotiateClient(
        input: InputStream,
        output: OutputStream,
        credentials: SocksCredentials?,
        peerPort: Int = 0,
    ) {
        if (credentials != null && peerPort == LOCAL_ROUTER_PORT && LocalSocksAuth.isInternal(credentials)) {
            negotiateRouterProofClient(input, output, credentials)
            return
        }
        val method = if (credentials != null) METHOD_USER_PASS else METHOD_NO_AUTH
        output.write(byteArrayOf(VERSION.toByte(), 1, method.toByte()))
        output.flush()
        val version = readByte(input)
        val selected = readByte(input)
        if (version != VERSION || selected != method) {
            throw EOFException("socks method rejected: $version/$selected")
        }
        if (credentials == null) return
        val user = credentials.username.toByteArray(Charsets.UTF_8)
        val pass = credentials.password.toByteArray(Charsets.UTF_8)
        require(user.size in 1..255 && pass.size in 1..255) { "socks credentials length is invalid" }
        output.write(byteArrayOf(USER_PASS_VERSION.toByte(), user.size.toByte()) + user + byteArrayOf(pass.size.toByte()) + pass)
        output.flush()
        readByte(input)
        if (readByte(input) != 0) throw EOFException("socks authentication failed")
    }

    /** Client side of the router proof; never writes [internal] to the stream. */
    fun negotiateRouterProofClient(input: InputStream, output: OutputStream, internal: SocksCredentials) {
        output.write(byteArrayOf(VERSION.toByte(), 1, METHOD_ROUTER_PROOF.toByte()))
        output.flush()
        val version = readByte(input)
        val selected = readByte(input)
        if (version != VERSION || selected != METHOD_ROUTER_PROOF) {
            throw UntrustedSocksRouterException("router listener did not select the proof method")
        }
        val nonceC = ByteArray(ROUTER_NONCE_BYTES).also { secureRandom.nextBytes(it) }
        output.write(byteArrayOf(ROUTER_PROOF_VERSION.toByte()) + nonceC)
        output.flush()
        if (readByte(input) != ROUTER_PROOF_VERSION) throw UntrustedSocksRouterException("bad router proof version")
        val nonceS = ByteArray(ROUTER_NONCE_BYTES).also { readFully(input, it) }
        val serverMac = ByteArray(ROUTER_MAC_BYTES).also { readFully(input, it) }
        if (!MessageDigest.isEqual(serverMac, routerProofMac(internal.password, ROUTER_SERVER_LABEL, nonceC, nonceS))) {
            throw UntrustedSocksRouterException("bad router proof")
        }
        output.write(routerProofMac(internal.password, ROUTER_CLIENT_LABEL, nonceC, nonceS))
        output.flush()
        val statusVersion = readByte(input)
        if (statusVersion != ROUTER_PROOF_VERSION || readByte(input) != 0) {
            throw EOFException("router proof rejected")
        }
    }

    /**
     * Server side of the router proof after [METHOD_ROUTER_PROOF] was offered. Returns true when
     * the client proved knowledge of [internal]; replies with a failure status otherwise.
     */
    fun negotiateRouterProofServer(input: InputStream, output: OutputStream, internal: SocksCredentials): Boolean {
        output.write(byteArrayOf(VERSION.toByte(), METHOD_ROUTER_PROOF.toByte()))
        output.flush()
        if (readByte(input) != ROUTER_PROOF_VERSION) throw EOFException("bad router proof version")
        val nonceC = ByteArray(ROUTER_NONCE_BYTES).also { readFully(input, it) }
        val nonceS = ByteArray(ROUTER_NONCE_BYTES).also { secureRandom.nextBytes(it) }
        output.write(byteArrayOf(ROUTER_PROOF_VERSION.toByte()) + nonceS + routerProofMac(internal.password, ROUTER_SERVER_LABEL, nonceC, nonceS))
        output.flush()
        val clientMac = ByteArray(ROUTER_MAC_BYTES).also { readFully(input, it) }
        val ok = MessageDigest.isEqual(clientMac, routerProofMac(internal.password, ROUTER_CLIENT_LABEL, nonceC, nonceS))
        output.write(byteArrayOf(ROUTER_PROOF_VERSION.toByte(), if (ok) 0 else 1))
        output.flush()
        return ok
    }

    internal fun routerProofMac(password: String, label: String, nonceC: ByteArray, nonceS: ByteArray): ByteArray {
        val mac = Mac.getInstance("HmacSHA256")
        mac.init(SecretKeySpec(password.toByteArray(Charsets.UTF_8), "HmacSHA256"))
        mac.update(label.toByteArray(Charsets.US_ASCII))
        mac.update(nonceC)
        mac.update(nonceS)
        return mac.doFinal()
    }

    /**
     * Server side. When [accepted] is empty, no-auth is accepted. Otherwise the client must offer
     * user/pass and present one of the accepted credential pairs. Returns the matched credentials
     * (or null for no-auth); throws after replying with a failure when authentication fails.
     */
    fun negotiateServer(input: InputStream, output: OutputStream, accepted: List<SocksCredentials>): SocksCredentials? {
        if (readByte(input) != VERSION) throw EOFException("bad socks version")
        val count = readByte(input)
        val methods = ByteArray(count)
        readFully(input, methods)
        val offered = methods.map { it.toInt() and BYTE_MASK }.toSet()
        if (accepted.isEmpty()) {
            if (METHOD_NO_AUTH !in offered) {
                output.write(byteArrayOf(VERSION.toByte(), METHOD_NO_ACCEPTABLE.toByte()))
                output.flush()
                throw EOFException("socks client offered no no-auth method")
            }
            output.write(byteArrayOf(VERSION.toByte(), METHOD_NO_AUTH.toByte()))
            output.flush()
            return null
        }
        if (METHOD_USER_PASS !in offered) {
            output.write(byteArrayOf(VERSION.toByte(), METHOD_NO_ACCEPTABLE.toByte()))
            output.flush()
            throw EOFException("socks client did not offer user/pass")
        }
        output.write(byteArrayOf(VERSION.toByte(), METHOD_USER_PASS.toByte()))
        output.flush()
        return readUserPass(input, output, accepted)
    }

    /** Reads an RFC 1929 request (after user/pass was selected) and replies with the status. */
    fun readUserPass(input: InputStream, output: OutputStream, accepted: List<SocksCredentials>): SocksCredentials {
        if (readByte(input) != USER_PASS_VERSION) throw EOFException("bad socks auth version")
        val user = ByteArray(readByte(input)).also { readFully(input, it) }.toString(Charsets.UTF_8)
        val pass = ByteArray(readByte(input)).also { readFully(input, it) }.toString(Charsets.UTF_8)
        val matched = accepted.firstOrNull {
            constantTimeEquals(it.username, user) and constantTimeEquals(it.password, pass)
        }
        output.write(byteArrayOf(USER_PASS_VERSION.toByte(), if (matched != null) 0 else 1))
        output.flush()
        return matched ?: throw EOFException("socks authentication failed")
    }

    private fun readByte(input: InputStream): Int {
        val value = input.read()
        if (value < 0) throw EOFException()
        return value
    }

    private fun readFully(input: InputStream, buffer: ByteArray) {
        var offset = 0
        while (offset < buffer.size) {
            val read = input.read(buffer, offset, buffer.size - offset)
            if (read < 0) throw EOFException()
            offset += read
        }
    }
}
